services:
  trainer:
    build: .
    env_file: .env
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
      - DATASET_NAME=${DATASET_NAME}
      - DATASET_VERSION=${DATASET_VERSION}
      - EMBED_SIZE=${EMBED_SIZE}
      - HIDDEN_SIZE=${HIDDEN_SIZE}
      - NUM_LAYERS=${NUM_LAYERS}
      - DROPOUT=${DROPOUT}
      - FREEZE_ENCODER=${FREEZE_ENCODER}
      - MAX_EPOCHS=${MAX_EPOCHS}
      - PATIENCE=${PATIENCE}
      - BATCH_SIZE=${BATCH_SIZE}
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./datasets:/app/datasets
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    secrets:
      - wandb_api_key

secrets:
  wandb_api_key:
    file: ./secrets.txt
