services:
  trainer:
    build: 
      context: .
      args:
        - NVIDIA_CUDA_VERSION=12.6
    runtime: nvidia
    env_file: .env
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./datasets:/app/datasets
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    secrets:
      - source: wandb_api_key
        target: wandb_api_key

secrets:
  wandb_api_key:
    file: ./secrets.txt